export default {
    LEFT_TOP: 'LEFT_TOP',
    CENTER_TOP: 'CENTER_TOP',
    RIGHT_TOP: 'RIGHT_TOP',
    LEFT_MIDDLE: 'LEFT_MIDDLE',
    CENTER_MIDDLE: 'CENTER_MIDDLE',
    RIGHT_MIDDLE: 'RIGHT_MIDDLE',
    LEFT_BOTTOM: 'LEFT_BOTTOM',
    CENTER_BOTTOM: 'CENTER_BOTTOM',
    RIGHT_BOTTOM: 'RIGHT_BOTTOM',
};
