const colors = [
    {
        name: 'Minimal',
        contrastColor: '#323232',
        colors: ['#ffffff'],
    },
    {
        name: 'Minimal Inverted',
        contrastColor: '#fff',
        colors: ['#000'],
    },
    {
        name: 'Turquoise',
        contrastColor: '#fff',
        colors: ['#1abc9c'],
    },
    {
        name: 'Emerald',
        contrastColor: '#fff',
        colors: ['#2ecc71'],
    },
    {
        name: 'Peter river',
        contrastColor: '#fff',
        colors: ['#3498db'],
    },
    {
        name: 'Amethyst',
        contrastColor: '#fff',
        colors: ['#9b59b6'],
    },
    {
        name: 'Wet asphalt',
        contrastColor: '#fff',
        colors: ['#34495e'],
    },
    {
        name: 'Sun flower',
        contrastColor: '#fff',
        colors: ['#f1c40f'],
    },
    {
        name: 'Orange',
        contrastColor: '#fff',
        colors: ['#f39c12'],
    },
    {
        name: 'Carrot',
        contrastColor: '#fff',
        colors: ['#e67e22'],
    },
    {
        name: 'Pumpkin',
        contrastColor: '#fff',
        colors: ['#d35400'],
    },
    {
        name: 'Alizarin',
        contrastColor: '#fff',
        colors: ['#e74c3c'],
    },
    {
        name: 'Pomegranate',
        contrastColor: '#fff',
        colors: ['#c0392b'],
    },
    {
        name: 'Concrete',
        contrastColor: '#fff',
        colors: ['#95a5a6'],
    },
    {
        name: 'Harmonic Energy',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#16A085', '#F4D03F'],
    },
    {
        name: 'Playing with Reds',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#D31027', '#EA384D'],
    },
    {
        name: 'Sunny Days',
        contrastColor: '#FF5600',
        angle: 180,
        colors: ['#EDE574', '#E1F5C4'],
    },
    {
        name: 'Green Beach',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#02AAB0', '#00CDAC'],
    },
    {
        name: 'Intuitive Purple',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#DA22FF', '#9733EE'],
    },
    {
        name: 'Emerald Water',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#348F50', '#56B4D3'],
    },
    {
        name: 'Rose Water',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#E55D87', '#5FC3E4'],
    },
    {
        name: 'Mango Pulp',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#F09819', '#EDDE5D'],
    },
    {
        name: 'Bloody Mary',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#FF512F', '#DD2476'],
    },
    {
        name: 'Aubergine',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#AA076B', '#61045F'],
    },
    {
        name: 'Aqua Marine',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#1A2980', '#26D0CE'],
    },
    {
        name: 'Sunrise',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#FF512F', '#F09819'],
    },
    {
        name: 'Sea Weed',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#4CB8C4', '#3CD3AD'],
    },
    {
        name: 'Pinky',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#DD5E89', '#F7BB97'],
    },
    {
        name: 'Cherry',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#EB3349', '#F45C43'],
    },
    {
        name: 'Mojito',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#1D976C', '#93F9B9'],
    },
    {
        name: 'Juicy Orange',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#FF8008', '#FFC837'],
    },
    {
        name: 'Mirage',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#16222A', '#3A6073'],
    },
    {
        name: 'Steel Gray',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#1F1C2C', '#928DAB'],
    },
    {
        name: 'Kashmir',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#614385', '#516395'],
    },
    {
        name: 'Electric Violet',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#4776E6', '#8E54E9'],
    },
    {
        name: 'Venice Blue',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#085078', '#85D8CE'],
    },
    {
        name: 'Moss',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#134E5E', '#71B280'],
    },
    {
        name: 'Shroom Haze',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#5C258D', '#4389A2'],
    },
    {
        name: 'Mystic',
        contrastColor: '#111',
        angle: 180,
        colors: ['#757F9A', '#D7DDE8'],
    },
    {
        name: 'Midnight City',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#232526', '#414345'],
    },
    {
        name: 'Sea Blizz',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#1CD8D2', '#93EDC7'],
    },
    {
        name: 'Titanium',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#283048', '#859398'],
    },
    {
        name: 'Mantle',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#24C6DC', '#514A9D'],
    },
    {
        name: 'Peach',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#ED4264', '#FFEDBC'],
    },
    {
        name: 'Clouds',
        contrastColor: '#777',
        angle: 180,
        colors: ['#ECE9E6', '#FFFFFF'],
    },
    {
        name: 'Stellar',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#7474BF', '#348AC7'],
    },
    {
        name: 'Bourbon',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#EC6F66', '#F3A183'],
    },
    {
        name: 'Influenza',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#C04848', '#480048'],
    },
    {
        name: 'Shrimpy',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#e43a15', '#e65245'],
    },
    {
        name: 'Miaka',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#FC354C', '#0ABFBC'],
    },
    {
        name: 'Pinot Noir',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#4b6cb7', '#182848'],
    },
    {
        name: 'Day Tripper',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#f857a6', '#ff5858'],
    },
    {
        name: 'Namn',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#a73737', '#7a2828'],
    },
    {
        name: 'A Lost Memory',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#DE6262', '#FFB88C'],
    },
    {
        name: 'Jonquil',
        contrastColor: '#711',
        angle: 180,
        colors: ['#FFEEEE', '#DDEFBB'],
    },
    {
        name: 'Kyoto',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#c21500', '#ffc500'],
    },
    {
        name: 'Aqualicious',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#50C9C3', '#96DEDA'],
    },
    {
        name: 'Moor',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#616161', '#9bc5c3'],
    },
    {
        name: 'Almost',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#ddd6f3', '#faaca8'],
    },
    {
        name: 'Reef',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#00d2ff', '#3a7bd5'],
    },
    {
        name: 'Dirty Fog',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#B993D6', '#8CA6DB'],
    },
    {
        name: 'Virgin',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#C9FFBF', '#FFAFBD'],
    },
    {
        name: 'Ash',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#606c88', '#3f4c6b'],
    },
    {
        name: 'Parklife',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#ADD100', '#7B920A'],
    },
    {
        name: 'Dance To Forget',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#FF4E50', '#F9D423'],
    },
    {
        name: 'Neon Life',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#B3FFAB', '#12FFF7'],
    },
    {
        name: 'Amethyst',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#9D50BB', '#6E48AA'],
    },
    {
        name: 'Cheer Up Emo Kid',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#556270', '#FF6B6B'],
    },
    {
        name: 'Friday',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#83a4d4', '#b6fbff'],
    },
    {
        name: 'Endless River',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#43cea2', '#185a9d'],
    },
    {
        name: 'Pastel Orange at the Sun',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#ffb347', '#ffcc33'],
    },
    {
        name: 'Turquoise flow',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#136a8a', '#267871'],
    },
    {
        name: 'Piglet',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#ee9ca7', '#ffdde1'],
    },
    {
        name: 'Lizard',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#304352', '#d7d2cc'],
    },
    {
        name: 'Passion',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#e53935', '#e35d5b'],
    },
    {
        name: 'Back To Earth',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#00C9FF', '#92FE9D'],
    },
    {
        name: 'Deep Purple',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#673AB7', '#512DA8'],
    },
    {
        name: 'Little Leaf',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#76b852', '#8DC26F'],
    },
    {
        name: 'Light Orange',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#FFB75E', '#ED8F03'],
    },
    {
        name: 'Green and Blue',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#c2e59c', '#64b3f4'],
    },
    {
        name: 'Blush',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#B24592', '#F15F79'],
    },
    {
        name: 'Purplin',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#6a3093', '#a044ff'],
    },
    {
        name: 'Pale Wood',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#eacda3', '#d6ae7b'],
    },
    {
        name: 'Haikus',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#fd746c', '#ff9068'],
    },
    {
        name: 'Pizelex',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#114357', '#F29492'],
    },
    {
        name: 'Nighthawk',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#2980b9', '#2c3e50'],
    },
    {
        name: 'Deep Space',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#000000', '#434343'],
    },
    {
        name: 'Decent',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#4CA1AF', '#C4E0E5'],
    },
    {
        name: 'Colors Of Sky',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#E0EAFC', '#CFDEF3'],
    },
    {
        name: 'Red Ocean',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#1D4350', '#A43931'],
    },
    {
        name: 'Tranquil',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#EECDA3', '#EF629F'],
    },
    {
        name: 'Transfile',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#16BFFD', '#CB3066'],
    },
    {
        name: 'Sylvia',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#ff4b1f', '#ff9068'],
    },
    {
        name: 'Sweet Morning',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#FF5F6D', '#FFC371'],
    },
    {
        name: 'Bright Vault',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#00d2ff', '#928DAB'],
    },
    {
        name: 'Solid Vault',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#3a7bd5', '#3a6073'],
    },
    {
        name: 'Sunset',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#0B486B', '#F56217'],
    },
    {
        name: 'Grapefruit Sunset',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#e96443', '#904e95'],
    },
    {
        name: 'Mauve',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#42275a', '#734b6d'],
    },
    {
        name: 'Lush',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#56ab2f', '#a8e063'],
    },
    {
        name: 'Firewatch',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#cb2d3e', '#ef473a'],
    },
    {
        name: 'Blood Red',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#f85032', '#e73827'],
    },
    {
        name: '50 Shades of Grey',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#bdc3c7', '#2c3e50'],
    },
    {
        name: 'Dania',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#BE93C5', '#7BC6CC'],
    },
    {
        name: 'Limeade',
        contrastColor: '#0c0c0c',
        angle: 180,
        colors: ['#A1FFCE', '#FAFFD1'],
    },
    {
        name: 'Azure Pop',
        contrastColor: '#fff',
        angle: 180,
        colors: ['#ef32d9', '#89fffd'],
    },
    {
        name: 'Blade Runner',
        contrastColor: '#00C793',
        angle: 180,
        colors: ['#000', '#333'],
    },
].map((color) => ({
    ...color,
    id: `color-${color.angle || 0}-${color.colors.join('')}`,
}));

export default colors;
